spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
   #     show_sql: true #sysout으로 출력
        format_sql: true #

server:
  port: 8083

logging.level:
  org.hibernate.SQL: debug #logger로